apiVersion: v1
kind: PersistentVolume
metadata:
  name: ahf-pv
  annotations:
    "volume.alpha.kubernetes.io/node-affinity": '{
    "requiredDuringSchedulingIgnoredDuringExecution": {
    "nodeSelectorTerms": [
      { "matchExpressions": [
        { "key": "kubernetes.io/hostname",
          "operator": "In",
          "values": ["cloud2"]
        }
      ]}
     ]}
    }'
spec:
  capacity:
    storage: 50Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  local:
    path: /tmp/ahf-data