apiVersion: v1
kind: Service
metadata:
  name: ahf-hiof
spec:
  selector:
    app: ahf
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: bind-service
spec:
  selector:
    app: ahf
    role: bind
  ports:
  - name: port1
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 30053
  - name: port2
    protocol: UDP
    port: 123
    targetPort: 123
    nodePort: 30123
  - name: port3
    protocol: UDP
    port: 31935
    targetPort: 31935
    nodePort: 31935
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-deployment
  selector:
    matchLabels:
      app: ahf
      role: bind
  replicas: 1
  template:
    metadata:
      labels:
        app: ahf
        role: bind
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cloud4
      hostname: dns
      subdomain: ahf-hiof
      containers:
      - name: bind
        image: anlam/arrowhead:bindv2
        env:
        - name: LOCK_OUT_DIR
          value: "false"
        ports:
        - containerPort: 53
        - containerPort: 123
        - containerPort: 31935
        volumeMounts:
        - name: tsig-volume
          mountPath: /tsig
      volumes:
        - name: tsig-volume
          persistentVolumeClaim:
            claimName: tsig-pvc