apiVersion: v1
kind: Service
metadata:
  name: simplesd-service
spec:
  selector:
    app: ahf
    role: simplesd
  ports:
  - name: port1
    port: 5683
    targetPort: 5683
    nodePort: 30083
  - name: port2
    port: 8045
    targetPort: 8045
    nodePort: 30045
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplesd-deployment
spec:
  selector:
    matchLabels:
      app: ahf
      role: simplesd
  replicas: 1
  template:
    metadata:
      labels:
        app: ahf
        role: simplesd
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cloud4    
      hostname: simplesd
      subdomain: ahf-hiof
      containers:
      - name: simplesd
        image: anlam/arrowhead:simplesd
        env:
        - name: BROWSING_DOMAIN
          value: "ahf-hiof.res-lec.svc.cluster.local"
        - name: ORCHESTRATION_URL
          value: "https://glassfish.ahf-hiof.res-lec.svc.cluster.local:8181/orchestration/store"
        - name: AUTHORISATION_URL
          value: "https://glassfish.ahf-hiof.res-lec.svc.cluster.local:8181/authorisation"
        - name: WAIT_FOR_TLS_READY
          value: "true"
        - name: DNS_SERVER
          value: "dns.ahf-hiof.res-lec.svc.cluster.local"
        ports:
        - containerPort: 5683
        - containerPort: 8045
        volumeMounts:
        - name: tsig-volume
          mountPath: /tsig
        - name: tls-volume
          mountPath: /tls
      volumes:
        - name: tsig-volume
          persistentVolumeClaim:
            claimName: tsig-pvc
        - name: tls-volume
          persistentVolumeClaim:
            claimName: tls-pvc
            
        