apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tsig-pvc
spec:
  accessModes:
  - ReadWriteMany     
  resources:
     requests:
       storage: 10Mi   
  storageClassName: local-storage      